services:

  web:
    depends_on:
      - app
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - build:/usr/share/nginx/html
    ports:
      - '7077:7077'

  app:
    build: .
    volumes:
      - ./src:/frontend/src
      - build:/frontend/dist/healthy_lifestyle_net_fe/browser

volumes:
  build:
