export const Settings = {
  maxCategoryCount: 5,
  maxAdditionEventPhotoCount: 3,
  maxAdditionUserPhotoCount: 3,
  maxAnswerLength: 1000,
  minAnswerLength: 10,
  maxQuestionLength: 1000,
  minQuestionLength: 10,
  questionDefaultLimit: 4,
  eventDefaultLimit: 9,
  articlesDefaultLimit: 8,
  masterDefaultLimit: 4,
  maxCategoryTagCount: 10,
  passwordRegex: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]).{8,}$/,
  emailRegex: /^([-!#$%&'*+/=?^_`{}|~0-9A-Z]+(\.[-!#$%&'*+/=?^_`{}|~0-9A-Z]+)*|^"([\x01-\x08\x0b\x0c\x0e-\x1f!#-\[\]-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+[A-Z]{2,63}\.?$/i,
}
